# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PJH\Temp\pyQT\A\C\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(360, 240)
        self.pushButton_OK = QtWidgets.QPushButton(Form)
        self.pushButton_OK.setGeometry(QtCore.QRect(70, 200, 71, 23))
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.pushButton_Cancel = QtWidgets.QPushButton(Form)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(220, 200, 71, 23))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 301, 78))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 22, 24, 16))
        self.label.setObjectName("label")
        self.lineEdit_CIP = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_CIP.setGeometry(QtCore.QRect(90, 22, 161, 20))
        self.lineEdit_CIP.setObjectName("lineEdit_CIP")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 48, 36, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_CPort = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_CPort.setGeometry(QtCore.QRect(90, 48, 161, 20))
        self.lineEdit_CPort.setObjectName("lineEdit_CPort")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 110, 301, 78))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(30, 22, 24, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_SIP = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SIP.setGeometry(QtCore.QRect(90, 22, 161, 20))
        self.lineEdit_SIP.setObjectName("lineEdit_SIP")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(30, 48, 30, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_SPort = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SPort.setGeometry(QtCore.QRect(90, 48, 161, 20))
        self.lineEdit_SPort.setObjectName("lineEdit_SPort")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_OK.setText(_translate("Form", "确认"))
        self.pushButton_Cancel.setText(_translate("Form", "取消"))
        self.groupBox.setTitle(_translate("Form", "本机"))
        self.label.setText(_translate("Form", "IP："))
        self.label_2.setText(_translate("Form", "Port："))
        self.groupBox_2.setTitle(_translate("Form", "服务器"))
        self.label_3.setText(_translate("Form", "IP："))
        self.label_4.setText(_translate("Form", "Port:"))
